# Generated by Django 4.2.4 on 2024-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=1500, null=True)),
                ('company_name', models.CharField(blank=True, max_length=1500, null=True)),
                ('experience', models.CharField(blank=True, max_length=1500, null=True)),
                ('ctc', models.CharField(blank=True, max_length=1500, null=True)),
            ],
        ),
    ]
