# Generated by Django 4.2.4 on 2024-01-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_jobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='link',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
