# Generated by Django 4.2.4 on 2024-01-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_jobdetails_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='location',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
